[[pages]]
path = "home_content.py"
name = "Dealing Dashboard"
icon = "ğŸ "

[[pages]]
name = "Broker Stats"
icon = "ğŸ“ˆ"
is_section = true

[[pages]]
path = "pages/broker_stats/broker_flow.py"
name = "Broker Flow"
icon = "ğŸ”„"

[[pages]]
path = "pages/broker_stats/winning_trades.py"
name = "Winning Trades"
icon = "ğŸ†"

[[pages]]
name = "CDS"
icon = "ğŸ’¹"
is_section = true

[[pages]]
path = "pages/cds/best_brokers.py"
name = "Best Brokers"
icon = "ğŸŒŸ"

[[pages]]
path = "pages/cds/quotes.py"
name = "Quotes"
icon = "ğŸ’¬"
